port: 7000
apiKey: "<api_key>"
irodsServiceConfig:
  password: "test"
  zone: "TUG"
  ipcServices: false
ldapServiceConfig:
  host: "ldap://192.168.31.115:389/"
  admin: "cn=Manager,dc=example,dc=org"
  password: "notreal"
  baseDN: "dc=example,dc=org"
  everyoneGroup: "everyone"
  firstLoginPassword: "notreal"
users:
  testuser:
    mail: test.user@example.com
    password: testpass