port: 7000
irodsServiceConfig:
  password: "ksasagrybisdRPY1M"
  zone: "TUG"
  ipcServices: false
ldapServiceConfig:
  host: "ldap://192.168.31.115:389/"
  admin: "cn=Manager,dc=example,dc=org"
  password: "notreal"
  baseDN: "dc=example,dc=org"
  everyoneGroup: "everyone"
  firstLoginPassword: "notreal"
authConfig:
  apiKey: "<api_key>"
  users:
    test_user:
      mail: "test.user@example.com"
      password: "testpass"