port: 7000
irodsServiceConfig:
  password: "test"
  zone: "TUG"
  ipcServices: false
ldapServiceConfig:
  host: "ldap://192.168.31.115:389/"
  admin: "cn=Manager,dc=example,dc=org"
  password: "notreal"
  baseDN: "dc=example,dc=org"
  everyoneGroup: "everyone"
  firstLoginPassword: "notreal"
authConfig:
  apiKey: "<api_key>"
  tokenIssuer: "http://api-service.cyverse.at"
  users:
    test_user:
      mail: "test.user@example.com"
      password: "testpass"
userPortalServiceConfig:
  host: http://192.168.31.115:3000
  hmacKey: <SECRET> # portal equivalent in ENV config: HMAC_KEY
  divisor: 7 # portal equivalent in ENV config: HONEYPOT_DIVISOR
  # This field is used to compute the first and last name fields for api requests with
  # a specific formula. sending plain "first_name: test_name" will not work. By using this
  # divisor we make sure to send the correct fields that portal will understand.
  # (e.g. "7: test_name")