port: 7000
irodsServiceConfig:
  password: "test"
  zone: "TUG"
  ipcServices: false
ldapServiceConfig:
  host: "ldap://192.168.31.115:389/"
  admin: "cn=Manager,dc=example,dc=org"
  password: "notreal"
  baseDN: "dc=example,dc=org"
  everyoneGroup: "everyone"
  firstLoginPassword: "notreal"
authConfig:
  apiKey: "<api_key>"
  tokenIssuer: "http://api-service.cyverse.at"
  users:
    test_user:
      mail: "test.user@example.com"
      password: "testpass"
userPortalServiceConfig:
  host: http://192.168.31.115:3000
  hmacKey: <SECRET>
  divisor: 7
