services:
  db:
    image: postgres:16
    pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  keycloak:
    build:
        context: ../event-listener/
        dockerfile: Dockerfile.test
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_PASSWORD: keycloak
      KC_SPI_EVENTS_LISTENER_LOGIN_LISTENER_API_SERVICE_HOST: http://192.168.31.115:7000
    ports:
      - "8087:8080"